PATH=/usr/local/bin:./bin/:$PATH

source ~/Dropbox/configuration/custom_settings.sh

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# added by travis gem
[ -f /Users/kevin/.travis/travis.sh ] && source /Users/kevin/.travis/travis.sh
