#!/usr/bin/env bash

function help() {
  echo "COMMANDS:"
  echo "  available   see available governors"
  echo "  active      see the active governor"
  echo "  set <name>  set a new governor"
  echo "  help        show this help screen"
}

function available() {
  sed -e 's/ /\n/g' < /usr/bin/cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
}

function active() {
  /usr/bin/cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
}

function activate() {
  echo "$1" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
}


if [ -z "$1" ] || [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "Sets the CPU scaling governor"
  echo
  echo "USAGE: $0 <command>"
  echo
  help
  exit
fi

if [ "$1" == "available" ]; then
  echo Available CPU scaling governors:
  available | while read -r governor; do
    echo "- $governor"
  done
  exit
fi

if [ "$1" == "active" ]; then
  echo Currently active CPU scaling governor: "$(active)"
  exit
fi

if [ "$1" == "set" ]; then
  if [ -z "$2" ]; then
    help
  fi
  MATCH=$(available | grep "\b$2\b")
  if [ -z "$MATCH" ]; then
    echo Not a valid governor: "$2"
    echo
    echo Available governors:
    available | while read -r governor; do
      echo "- $governor"
    done
    exit 1
  fi
  echo Setting CPU governor to "$2"
  activate "$2"
  echo
  echo Current CPU governor is now: "$(active)"
  exit
fi

echo Unknown command: "$1"
echo
help
exit 1
