#!/usr/bin/env bash
set -e

# check argument
if [ "$1" == "" ]; then
echo
  echo "Kevin's back-up script to external media"
  echo
  echo "Usage: backup <target folder>"
  echo
  echo "Possible locations:"
  ls -1 /Volumes | grep -v "^Mac$"
  exit 1
fi
target=$1


function run_rsync {
  echo
  echo
  tput bold
  echo "Backing up $1"
  tput sgr0
  rsync -a --delete --progress "$1" "/Volumes/$target"
}

if [ ! -d "/Volumes/$target" ]; then
  echo "The provided target (/Volumes/$target) does not exist"
  echo
  exit 1
fi

run_rsync "Music"
run_rsync "Pictures"

echo
echo
tput bold
echo Please copy the iMovie Library manually
echo
echo "ALL DONE"
tput sgr0
