#!/usr/bin/env bash
set -e

# This job displays whether there are uncommitted updates to the dot files

changes=$(cd "$HOME/.config" ; git -c color.status=always status --short)
if [ ! -z "$changes" ]; then
  tput bold
  echo UNCOMITTED DOTFILE CHANGES
  tput sgr0
  echo
  echo "$changes"
  echo
  echo
fi
