#!/usr/bin/env bash

# path of the configuration file
SETTINGS_PATH="$HOME/.config/brightness"

# how much to change the brightness up or down
STEP_SIZE=5

# the control code for brightness in ddccontrol
BRIGHTNESS_CONTROL="0x10"


# parses the CLI args and provides the command to run
function parse_args() {
  case $1 in
    '-r') echo "refresh"         ;; # refresh before running the app
    '--refresh') echo "refresh"  ;;
    'show-all') echo "show_all"  ;; # show all monitor codes and exit
    'adjust') echo "adjust"      ;; # adjust the brightness
    '') echo "adjust"            ;; # adjust in the default command
    '-h') echo "usage"           ;; # print usage instructions before running the app
    'help') echo "usage"         ;;
    *) echo "cli-usage"          ;; # unknown command, print CLI usage and exit
  esac
}

# displays program usage instructions
function usage() {
  echo "Changes the brightness setting on the external monitor."
  echo "- UP/DOWN adjusts the brightness in increments of $STEP_SIZE%"
  echo "- HOME/END sets the max/min brightness"
  echo "- ENTER or Q to exit"
}

# displays CLI arguments
function cli_usage() {
  echo "Usage: $0 [options]"
  echo
  echo "Available options:"
  echo "--help/-h: print usage instructions before running"
  echo "--refresh/-r: refresh the cached monitor setup before adjusting the brightness"
}

function detect_monitor() {
  sudo ddccontrol -p 2> /dev/null | grep "Reading EDID and initializing DDC/CI at bus" | grep -o "dev:/dev/i2c-[0-9]"
}

function detect_brightness() {
  monitor=$1
  sudo ddccontrol "$monitor" -r $BRIGHTNESS_CONTROL 2> /dev/null | grep "Control 0x10" | grep -oE "\+\/[0-9]+\/" | grep -Eo "[0-9]+"
}

# makes the external monitor one step brighter
function brighter() {
  monitor=$1
  brightness=$((brightness+STEP_SIZE))
  if [ "$brightness" -gt "100" ]; then
    brightness=100
  fi
  sudo ddccontrol "$monitor" -r $BRIGHTNESS_CONTROL -w "$brightness" &> /dev/null &
  progressbar "$brightness"
}

# makes the external monitor one step darker
function darker() {
  monitor=$1
  brightness=$((brightness-STEP_SIZE))
  if [ "$brightness" -lt "0" ]; then
    brightness=0
  fi
  sudo ddccontrol "$monitor" -r $BRIGHTNESS_CONTROL -w "$brightness" &> /dev/null &
  progressbar "$brightness"
}

# sets the external monitor to the given brightness level
function set() {
  monitor=$1
  brightness=$2
  sudo ddccontrol "$monitor" -r $BRIGHTNESS_CONTROL -w "$brightness" &> /dev/null &
  progressbar "$brightness"
}

# displays all available monitor codes
function available_codes() {
  sudo ddccontrol -p
}

# reads the persistent configuration file
function load_settings() {
  if [ -f "$SETTINGS_PATH" ]; then
    cat "$SETTINGS_PATH"
  fi
}

# saves the detected monitor configuration into the persistent settings file
function save_settings() {
  monitor=$1
  echo "$monitor" >> "$SETTINGS_PATH"
}

function progressbar() {
  level=$1
  echo -n "$level "
  for i in {0..100}; do
    if [ "$i" -eq "$level" ]; then
      echo -n "█"
    else
      echo -n "-"
    fi
  done
  echo -n "  "
  printf "\r"
}

command=$(parse_args "$1")

if [ "$command" = "cli_usage" ]; then
  cli_usage
  exit 1
fi

if [ "$command" = "usage" ]; then
  print_usage
fi

if [ "$command" = "show_all" ]; then
  show_all
  exit
fi

if [ "$command" = "refresh" ]; then
  if [ -f "$SETTINGS_PATH" ]; then
    rm "$SETTINGS_PATH"
  fi
fi

monitor=$(load_settings)
if [ -z "$monitor" ]; then
  echo -n "detecting monitor setup ... "
  monitor=$(detect_monitor)
  echo "$monitor"
  if [ -z "$monitor" ]; then
    echo
    echo "Could not identify an external monitor"
    exit 1
  fi
  save_settings "$monitor"
fi

tput civis

brightness=$(detect_brightness "$monitor") 2> /dev/null
progressbar "$brightness"

escape_char=$(printf "\u1b")
while true; do
  read -rsn1 mode       # get 1 character
  if [[ $mode == "$escape_char" ]]; then
      read -rsn2 mode   # read 2 more chars
  fi
  case $mode in
      'q') break ;;
      '') break ;;
      '[A') brighter "$monitor"  ;;  # up
      '[B') darker "$monitor"    ;;  # down
      '[D') darker "$monitor"  ;;  # left
      '[C') brighter "$monitor"    ;;  # right
      '[H') set "$monitor" 100   ;;  # home
      '[F') set "$monitor" 0     ;;  # end
      *) >&2 echo 'ERR bad input'; exit ;;
  esac
done

tput cnorm
