#!/usr/bin/env bash
/usr/bin/code --uninstall-extension 2gua.rainbow-brackets
/usr/bin/code --uninstall-extension alexkrechik.cucumberautocomplete
/usr/bin/code --uninstall-extension bungcip.better-toml
/usr/bin/code --uninstall-extension dawhite.mustache
/usr/bin/code --uninstall-extension dbaeumer.vscode-eslint
/usr/bin/code --uninstall-extension esbenp.prettier-vscode
/usr/bin/code --uninstall-extension golang.go
/usr/bin/code --uninstall-extension kevgo.vscode-markdown-ide
/usr/bin/code --uninstall-extension kumar-harsh.graphql-for-vscode
/usr/bin/code --uninstall-extension matklad.rust-analyzer
/usr/bin/code --uninstall-extension travisthetechie.write-good-linter
/usr/bin/code --uninstall-extension vscodevim.vim
/usr/bin/code --uninstall-extension yzhang.markdown-all-in-one
/usr/bin/code --uninstall-extension znck.grammarly
