#!/usr/bin/env bash
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bungcip.better-toml
code --install-extension dbaeumer.vscode-eslint
code --install-extension dprint.dprint
code --install-extension golang.go
code --install-extension kevgo.vscode-markdown-ide
code --install-extension liviuschera.noctis
code --install-extension redhat.vscode-yaml
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension usernamehw.errorlens
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
